#!/bin/sh
systemctl disable timekpr
systemctl stop timekpr
systemctl reload dbus
if [ -d /usr/share/pyshared/timekpr ];
then
    find /usr/share/pyshared/timekpr -type d -name '__pycache__' -exec rm -rf {} \; -prune
    find /usr/share/pyshared/timekpr -iname '*.pyc' -exec rm {} \;
fi
